# Generated by Django 4.0.2 on 2022-02-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('loginid', models.IntegerField(db_column='LoginID')),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=50, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=2, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('headportrait', models.CharField(db_column='HeadPortrait', max_length=50)),
                ('phonenumber', models.IntegerField(blank=True, db_column='PhoneNumber', null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=50, null=True)),
                ('bloodtype', models.CharField(blank=True, db_column='BloodType', max_length=4, null=True)),
                ('datebirth', models.DateTimeField(blank=True, db_column='DateBirth', null=True)),
                ('constellation', models.CharField(blank=True, db_column='Constellation', max_length=5, null=True)),
                ('shengxiao', models.CharField(blank=True, db_column='ShengXiao', max_length=2, null=True)),
                ('sign', models.CharField(blank=True, db_column='Sign', max_length=100, null=True)),
                ('profession', models.CharField(blank=True, db_column='Profession', max_length=50, null=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=50, null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
