# Generated by Django 4.0.3 on 2022-04-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addfriends',
            fields=[
                ('applicantid', models.IntegerField(db_column='ApplicantID', primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(db_column='ObjectID')),
                ('addway', models.CharField(blank=True, db_column='Addway', max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=50, null=True)),
                ('sendtime', models.CharField(blank=True, db_column='Sendtime', max_length=50, null=True)),
                ('responsetime', models.CharField(blank=True, db_column='Responsetime', max_length=50, null=True)),
                ('rep_results', models.IntegerField(db_column='Rep_results')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('relationid', models.IntegerField(db_column='RelationID', primary_key=True, serialize=False)),
                ('friendid', models.IntegerField(db_column='FriendID')),
                ('userid', models.IntegerField(db_column='UserID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('friendtypeid', models.IntegerField(db_column='FriendTypeID')),
                ('friendgroupsid', models.IntegerField(db_column='FriendGroupsID')),
            ],
        ),
        migrations.CreateModel(
            name='FriendsGroup',
            fields=[
                ('groupid', models.AutoField(db_column='GroupId', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='UserID')),
                ('groupname', models.CharField(blank=True, db_column='GroupName', max_length=50, null=True)),
                ('serialnumber', models.IntegerField(db_column='SerialNumber')),
                ('createtime', models.CharField(blank=True, db_column='CreateTime', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FriendType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(db_column='TypeName', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupid', models.IntegerField(db_column='GroupID', primary_key=True, serialize=False)),
                ('groupname', models.CharField(db_column='GroupName', max_length=10)),
                ('groupleaderid', models.CharField(blank=True, db_column='GroupleaderID', max_length=50, null=True)),
                ('groupavatars', models.CharField(blank=True, db_column='GroupAvatars', max_length=50, null=True)),
                ('groupintro', models.CharField(blank=True, db_column='GroupIntro', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('Messagesid', models.IntegerField(db_column='MessagesID', primary_key=True, serialize=False)),
                ('PostMessages', models.CharField(blank=True, db_column='PostMessages', max_length=500, null=True)),
                ('status', models.IntegerField(db_column='Status')),
                ('SendTime', models.CharField(blank=True, db_column='SendTime', max_length=50, null=True)),
                ('MessagesTypeID', models.IntegerField(db_column='MessagesTypeID')),
                ('FromUserID', models.IntegerField(db_column='FromUserID')),
                ('ToUserID', models.IntegerField(db_column='ToUserID')),
            ],
        ),
        migrations.CreateModel(
            name='Messageslist',
            fields=[
                ('Messageslistid', models.IntegerField(db_column='MessageslistID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='UserID')),
                ('objectid', models.IntegerField(db_column='ObjectID')),
                ('unreadnum', models.IntegerField(db_column='UnreadNum', default=0)),
                ('time', models.CharField(blank=True, db_column='Time', max_length=50, null=True)),
                ('messagestypeid', models.IntegerField(db_column='MessagesTypeID')),
                ('createtime', models.CharField(blank=True, db_column='CreateTime', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessagesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(db_column='TypeName', max_length=50)),
            ],
        ),
    ]
