# Generated by Django 4.0.2 on 2022-02-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addfriends',
            fields=[
                ('applicantid', models.IntegerField(db_column='ApplicantID')),
                ('objectid', models.IntegerField(db_column='ObjectID')),
                ('addway', models.CharField(blank=True, db_column='Addway', max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=50, null=True)),
                ('sendtime', models.CharField(blank=True, db_column='Sendtime', max_length=50, null=True)),
                ('responsetime', models.CharField(blank=True, db_column='Responsetime', max_length=50, null=True)),
                ('rep_results', models.IntegerField(db_column='Rep_results', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendid', models.IntegerField(db_column='FriendID')),
                ('userid', models.IntegerField(db_column='UserID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('friendtypeid', models.IntegerField(db_column='FriendTypeID')),
                ('friendgroupsid', models.IntegerField(db_column='FriendGroupsID')),
            ],
        ),
        migrations.CreateModel(
            name='FriendType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(db_column='TypeName', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(db_column='GroupName', max_length=10)),
                ('groupid', models.IntegerField(db_column='GroupID')),
                ('groupleaderid', models.CharField(blank=True, db_column='GroupleaderID', max_length=50, null=True)),
                ('groupavatars', models.CharField(blank=True, db_column='GroupAvatars', max_length=50, null=True)),
                ('groupintro', models.CharField(blank=True, db_column='GroupIntro', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostMessages', models.IntegerField(db_column='PostMessages')),
                ('status', models.IntegerField(db_column='status')),
                ('SendTime', models.CharField(blank=True, db_column='SendTime', max_length=50, null=True)),
                ('MessagesTypeID', models.IntegerField(db_column='MessagesTypeID')),
                ('FromUserID', models.IntegerField(db_column='FromUserID')),
                ('ToUserID', models.IntegerField(db_column='ToUserID')),
            ],
        ),
        migrations.CreateModel(
            name='Messageslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='UserID')),
                ('objectid', models.IntegerField(db_column='ObjectID')),
                ('isonline', models.IntegerField(db_column='IsOnline')),
                ('unread', models.IntegerField(db_column='Unread')),
                ('nickname', models.IntegerField(db_column='NickName')),
                ('headportrait', models.CharField(blank=True, db_column='HeadPortrait', max_length=50, null=True)),
                ('postmessages', models.CharField(blank=True, db_column='PostMessages', max_length=500, null=True)),
                ('status', models.IntegerField(db_column='status')),
                ('time', models.CharField(blank=True, db_column='Time', max_length=50, null=True)),
                ('messagestypeid', models.IntegerField(db_column='MessagesTypeID')),
                ('fromuserid', models.IntegerField(db_column='FromUserID')),
                ('touserid', models.IntegerField(db_column='ToUserID')),
                ('createtime', models.CharField(blank=True, db_column='CreateTime', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessagesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(db_column='TypeName', max_length=50)),
            ],
        ),
    ]
