# Generated by Django 4.0.2 on 2022-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsGroup',
            fields=[
                ('groupid', models.AutoField(db_column='GroupId', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='UserID')),
                ('groupname', models.CharField(blank=True, db_column='GroupName', max_length=50, null=True)),
                ('serialnumber', models.IntegerField(db_column='SerialNumber')),
                ('createtime', models.CharField(blank=True, db_column='CreateTime', max_length=50, null=True)),
            ],
        ),
    ]
